version: "3.8"

services:
  database:
    container_name: database
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

  server:
    container_name: server
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on: 
      - database
    env_file:
      - .env


volumes:
  db:
